=== MartinoMensio/DP2-Labs/Assignment_1/xsd/nffgInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://dp2.polito.it/nffgInfo" xmlns:tns="http://dp2.polito.it/nffgInfo" elementFormDefault="qualified">
	<element name="verifier">
		<complexType>
			<sequence>
				<element name="nffg" maxOccurs="unbounded" type="tns:nffg_t">
					<keyref name="link_src_keyref" refer="tns:node_key">
						<selector xpath="tns:links/tns:link/tns:src" />
						<field xpath="@ref" />
					</keyref>
					<keyref name="link_dst_keyref" refer="tns:node_key">
						<selector xpath="tns:links/tns:link/tns:dst" />
						<field xpath="@ref" />
					</keyref>
					<keyref name="policy_src_keyref" refer="tns:node_key">
						<selector xpath="tns:policies/tns:policy/tns:src" />
						<field xpath="@ref" />
					</keyref>
					<keyref name="policy_dst_keyref" refer="tns:node_key">
						<selector xpath="tns:policies/tns:policy/tns:dst" />
						<field xpath="@ref" />
					</keyref>
				</element>
			</sequence>
		</complexType>
		<key name="nffg_key">
			<selector xpath="tns:nffg" />
			<field xpath="@name" />
		</key>
		<key name="policy_key">
			<selector xpath="tns:nffg/tns:policies/tns:policy" />
			<field xpath="@name" />
		</key>
	</element>

	<complexType name="named_element_t">
		<attribute name="name" type="tns:name_t" use="required" />
	</complexType>

	<complexType name="nffg_t">
		<complexContent>
			<extension base="tns:named_element_t">
				<sequence>
					<element name="nodes">
						<complexType>
							<sequence>
								<element name="node" minOccurs="0" maxOccurs="unbounded" type="tns:node_t" />
							</sequence>
						</complexType>
						<key name="node_key">
							<selector xpath="tns:node" />
							<field xpath="@name" />
						</key>
					</element>
					<element name="links">
						<complexType>
							<sequence>
								<element name="link" minOccurs="0" maxOccurs="unbounded" type="tns:link_t" />
							</sequence>
						</complexType>
						<key name="link_key">
							<selector xpath="tns:link" />
							<field xpath="@name" />
						</key>
					</element>
					<element name="policies">
						<complexType>
							<sequence>
								<element name="policy" minOccurs="0" maxOccurs="unbounded" type="tns:policy_t" />
							</sequence>
						</complexType>
					</element>
				</sequence>
				<attribute name="updated" type="dateTime" use="required" />
			</extension>
		</complexContent>
	</complexType>

	<complexType name="node_t">
		<complexContent>
			<extension base="tns:named_element_t">
				<sequence>
					<element name="functionality" type="tns:functionality_t" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="link_t">
		<complexContent>
			<extension base="tns:named_element_t">
				<sequence>
					<element name="src" type="tns:node_ref_t" />
					<element name="dst" type="tns:node_ref_t" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="policy_t">
		<complexContent>
			<extension base="tns:link_t">
				<sequence>
					<element name="functionality" minOccurs="0" maxOccurs="unbounded" type="tns:functionality_t" />
					<element name="result" type="tns:result_t" minOccurs="0" />
				</sequence>
				<attribute name="positive" type="boolean" use="optional" default="true" />
			</extension>
		</complexContent>
	</complexType>

	<simpleType name="functionality_t">
		<restriction base="string">
			<enumeration value="CACHE" />
			<enumeration value="DPI" />
			<enumeration value="FW" />
			<enumeration value="MAIL_CLIENT" />
			<enumeration value="MAIL_SERVER" />
			<enumeration value="NAT" />
			<enumeration value="SPAM" />
			<enumeration value="VPN" />
			<enumeration value="WEB_CLIENT" />
			<enumeration value="WEB_SERVER" />
		</restriction>
	</simpleType>

	<complexType name="node_ref_t">
		<attribute name="ref" type="tns:name_t" use="required" />
	</complexType>

	<simpleType name="name_t">
		<restriction base="string">
			<pattern value="[a-zA-Z_][a-zA-Z\d_]*" />
		</restriction>
	</simpleType>

	<complexType name="result_t" mixed="true">
		<attribute name="satisfied" type="boolean" use="required" />
		<attribute name="verified" type="dateTime" use="required" />
	</complexType>

</schema>

=== MartinoMensio/DP2-Labs/Assignment_1/xsd/nffgInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<verifier xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="nffgInfo.xsd">
	<nffg name="Example1" updated="2002-05-30T09:00:00">
		<nodes>
			<node name="WebClient1">
				<functionality>WEB_CLIENT</functionality>
			</node>
			<node name="NAT1">
				<functionality>NAT</functionality>
			</node>
			<node name="Firewall1">
				<functionality>FW</functionality>
			</node>
			<node name="WebServer1">
				<functionality>WEB_SERVER</functionality>
			</node>
		</nodes>
		<links>
			<link name="link1">
				<src ref="WebClient1" />
				<dst ref="NAT1" />
			</link>
			<link name="link2">
				<src ref="NAT1" />
				<dst ref="Firewall1" />
			</link>
			<link name="link3">
				<src ref="Firewall1" />
				<dst ref="WebServer1" />
			</link>
		</links>
		<policies>
			<policy name="Policy1" expected="true">
				<src ref="WebClient1" />
				<dst ref="WebServer1" />
				<result satisfied="true" verified="2016-11-10T15:40:00+01:00">
					This is the message
				</result>
			</policy>
			<policy name="Policy2" expected="false">
				<src ref="WebServer1" />
				<dst ref="WebClient1" />
				<result satisfied="true" verified="2016-11-10T15:40:00+01:00">
					This is the message
				</result>
			</policy>
			<policy name="Policy3" expected="true">
				<src ref="WebClient1" />
				<dst ref="WebServer1" />
				<functionality>FW</functionality>
				<result satisfied="true" verified="2016-11-10T15:40:00+01:00">
					This is the message
				</result>
			</policy>
		</policies>
	</nffg>

	<nffg name="Example2" updated="2002-05-30T09:00:00">
		<nodes>
			<node name="WebClient1">
				<functionality>WEB_CLIENT</functionality>
			</node>
			<node name="NAT1">
				<functionality>NAT</functionality>
			</node>
			<node name="Firewall1">
				<functionality>FW</functionality>
			</node>
			<node name="WebServer1">
				<functionality>WEB_SERVER</functionality>
			</node>
		</nodes>
		<links>
			<link name="link1">
				<src ref="WebClient1" />
				<dst ref="NAT1" />
			</link>
			<link name="link2">
				<src ref="NAT1" />
				<dst ref="Firewall1" />
			</link>
			<link name="link3">
				<src ref="Firewall1" />
				<dst ref="WebServer1" />
			</link>
			<link name="link4">
				<src ref="NAT1" />
				<dst ref="WebClient1" />
			</link>
			<link name="link5">
				<src ref="Firewall1" />
				<dst ref="NAT1" />
			</link>
			<link name="link6">
				<src ref="WebServer1" />
				<dst ref="Firewall1" />
			</link>
		</links>
		<policies>
			<policy name="Policy1" expected="true">
				<src ref="WebClient1" />
				<dst ref="WebServer1" />
				<result satisfied="true" verified="2016-11-10T15:40:00+01:00">
					This is the message
				</result>
			</policy>
			<policy name="Policy2" expected="false">
				<src ref="WebServer1" />
				<dst ref="WebClient1" />
				<result satisfied="true" verified="2016-11-10T15:40:00+01:00">
					This is the message
				</result>
			</policy>
			<policy name="Policy3" expected="true">
				<src ref="WebClient1" />
				<dst ref="WebServer1" />
				<functionality>FW</functionality>
				<result satisfied="true" verified="2016-11-10T15:40:00+01:00">
					This is the message
				</result>
			</policy>
		</policies>
	</nffg>
</verifier>
