=== MartinoMensio/DP2-Labs/Assignment 1/dtd/nffgInfo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT nffgs (nffg)*>
<!ELEMENT nffg (nodes,links, policies?)>
<!ELEMENT nodes (node)*>
<!ELEMENT node (functionality)>
<!ELEMENT functionality EMPTY>
<!ELEMENT links (link)*>
<!ELEMENT link (src,dst)>
<!ELEMENT src EMPTY>
<!ELEMENT dst EMPTY>
<!ELEMENT name (#PCDATA)>
<!ELEMENT policies (policy)*>
<!ELEMENT policy (src,dst,functionality*)>


<!ATTLIST nffg
	name ID #REQUIRED>
<!ATTLIST node
	name ID #REQUIRED>
<!ATTLIST functionality
	type (firewall | DPI | NAT | antispam | web_cache | VPN_gateway | web_server | web_client | mail_server | mail_client) #REQUIRED>
<!ATTLIST link
	name ID #REQUIRED>
<!ATTLIST src
	id IDREF #REQUIRED>
<!ATTLIST dst
	id IDREF #REQUIRED>
<!ATTLIST policy
	name ID #REQUIRED
	result (positive|negative) "positive">

=== MartinoMensio/DP2-Labs/Assignment 1/dtd/nffgInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nffg SYSTEM "nffgInfo.dtd">

<nffgs>
	<nffg name="Example1" lastUpdate="2002-05-30T09:00:00">
		<nodes>
			<node name="WebClient1">
				<functionality type="WEB_CLIENT" />
			</node>
			<node name="NAT1">
				<functionality type="NAT" />
			</node>
			<node name="Firewall1">
				<functionality type="FW" />
			</node>
			<node name="WebServer1">
				<functionality type="WEB_SERVER" />
			</node>
		</nodes>
		<links>
			<link name="l001">
				<src ref="WebClient1" />
				<dst ref="NAT1" />
			</link>
			<link name="l002">
				<src ref="NAT1" />
				<dst ref="Firewall1" />
			</link>
			<link name="l003">
				<src ref="Firewall1" />
				<dst ref="WebServer1" />
			</link>
		</links>
		<policies>
			<policy name="Policy11" result="positive">
				<src ref="WebClient1" />
				<dst ref="WebServer1" />
			</policy>
			<policy name="Policy12" result="negative">
				<src ref="WebServer1" />
				<dst ref="WebClient1" />
			</policy>
			<policy name="Policy13" result="positive">
				<src ref="WebClient1" />
				<dst ref="WebServer1" />
				<functionality type="FW" />
			</policy>
		</policies>
	</nffg>
	
	<nffg name="Example2" lastUpdate="2002-05-30T09:00:00">
		<nodes>
			<node name="WebClient2">
				<functionality type="WEB_CLIENT" />
			</node>
			<node name="NAT2">
				<functionality type="NAT" />
			</node>
			<node name="Firewall2">
				<functionality type="FW" />
			</node>
			<node name="WebServer2">
				<functionality type="WEB_SERVER" />
			</node>
		</nodes>
		<links>
			<link name="l011">
				<src ref="WebClient2" />
				<dst ref="NAT2" />
			</link>
			<link name="l012">
				<src ref="NAT2" />
				<dst ref="Firewall2" />
			</link>
			<link name="l013">
				<src ref="Firewall2" />
				<dst ref="WebServer2" />
			</link>
			<link name="l014">
				<src ref="NAT2" />
				<dst ref="WebClient2" />
			</link>
			<link name="l015">
				<src ref="Firewall2" />
				<dst ref="NAT2" />
			</link>
			<link name="l016">
				<src ref="WebServer2" />
				<dst ref="Firewall2" />
			</link>
		</links>
		<policies>
			<policy name="Policy21" result="positive">
				<src ref="WebClient1" />
				<dst ref="WebServer1" />
			</policy>
			<policy name="Policy22" result="positive">
				<src ref="WebServer1" />
				<dst ref="WebClient1" />
			</policy>
			<policy name="Policy23" result="positive">
				<src ref="WebClient1" />
				<dst ref="WebServer1" />
				<functionality type="FW" />
			</policy>
		</policies>
	</nffg>

</nffgs>
