=== MartinoMensio/DP2-Labs/Assignment_1/dtd/nffgInfo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT verifier (nffg)*>
<!ELEMENT nffg (nodes,links,policies?)>
<!ELEMENT nodes (node)*>
<!ELEMENT node (functionality)>
<!ELEMENT functionality EMPTY>
<!ELEMENT links (link)*>
<!ELEMENT link (src,dst)>
<!ELEMENT src EMPTY>
<!ELEMENT dst EMPTY>
<!ELEMENT policies (policy)*>
<!ELEMENT policy (src,dst,functionality*,result?)>
<!ELEMENT result (#PCDATA)>


<!ATTLIST nffg
	name ID #REQUIRED
	updated CDATA #REQUIRED>
<!ATTLIST node
	name ID #REQUIRED>
<!ATTLIST functionality
	type (CACHE | DPI | FW | MAIL_CLIENT | MAIL_SERVER | NAT | SPAM | VPN | WEB_CLIENT | WEB_SERVER) #REQUIRED>
<!ATTLIST link
	name ID #REQUIRED>
<!ATTLIST src
	ref IDREF #REQUIRED>
<!ATTLIST dst
	ref IDREF #REQUIRED>
<!ATTLIST policy
	name ID #REQUIRED
	expected (true|false) "true">
<!ATTLIST result
	satisfied (true|false) #REQUIRED
	verified CDATA #REQUIRED>

=== MartinoMensio/DP2-Labs/Assignment_1/dtd/nffgInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE verifier SYSTEM "nffgInfo.dtd">

<verifier>
	<nffg name="Example1" updated="2002-05-30T09:00:00">
		<nodes>
			<node name="Example1_WebClient1">
				<functionality type="WEB_CLIENT" />
			</node>
			<node name="Example1_NAT1">
				<functionality type="NAT" />
			</node>
			<node name="Example1_Firewall1">
				<functionality type="FW" />
			</node>
			<node name="Example1_WebServer1">
				<functionality type="WEB_SERVER" />
			</node>
		</nodes>
		<links>
			<link name="Example1_l001">
				<src ref="Example1_WebClient1" />
				<dst ref="Example1_NAT1" />
			</link>
			<link name="Example1_l002">
				<src ref="Example1_NAT1" />
				<dst ref="Example1_Firewall1" />
			</link>
			<link name="Example1_l003">
				<src ref="Example1_Firewall1" />
				<dst ref="Example1_WebServer1" />
			</link>
		</links>
		<policies>
			<policy name="Example1_Policy1" expected="true">
				<src ref="Example1_WebClient1" />
				<dst ref="Example1_WebServer1" />
				<result satisfied="true" verified="2016-11-10T15:40:00+01:00">
					Ahahah
				</result>
			</policy>
			<policy name="Example1_Policy2" expected="false">
				<src ref="Example1_WebServer1" />
				<dst ref="Example1_WebClient1" />
			</policy>
			<policy name="Example1_Policy3" expected="true">
				<src ref="Example1_WebClient1" />
				<dst ref="Example1_WebServer1" />
				<functionality type="FW" />
			</policy>
		</policies>
	</nffg>

	<nffg name="Example2" updated="2002-05-30T09:00:00">
		<nodes>
			<node name="Example2_WebClient1">
				<functionality type="WEB_CLIENT" />
			</node>
			<node name="Example2_NAT1">
				<functionality type="NAT" />
			</node>
			<node name="Example2_Firewall1">
				<functionality type="FW" />
			</node>
			<node name="Example2_WebServer1">
				<functionality type="WEB_SERVER" />
			</node>
		</nodes>
		<links>
			<link name="Example2_l001">
				<src ref="Example2_WebClient1" />
				<dst ref="Example2_NAT1" />
			</link>
			<link name="Example2_l002">
				<src ref="Example2_NAT1" />
				<dst ref="Example2_Firewall1" />
			</link>
			<link name="Example2_l003">
				<src ref="Example2_Firewall1" />
				<dst ref="Example2_WebServer1" />
			</link>
			<link name="Example2_l004">
				<src ref="Example2_NAT1" />
				<dst ref="Example2_WebClient1" />
			</link>
			<link name="Example2_l005">
				<src ref="Example2_Firewall1" />
				<dst ref="Example2_NAT1" />
			</link>
			<link name="Example2_l006">
				<src ref="Example2_WebServer1" />
				<dst ref="Example2_Firewall1" />
			</link>
		</links>
		<policies>
			<policy name="Example2_Policy1" expected="true">
				<src ref="Example2_WebClient1" />
				<dst ref="Example2_WebServer1" />
			</policy>
			<policy name="Example2_Policy2" expected="true">
				<src ref="Example2_WebServer1" />
				<dst ref="Example2_WebClient1" />
			</policy>
			<policy name="Example2_Policy3" expected="true">
				<src ref="Example2_WebClient1" />
				<dst ref="Example2_WebServer1" />
				<functionality type="FW" />
			</policy>
		</policies>
	</nffg>

</verifier>
