=== MartinoMensio/DP2-Labs/Assignment 1/xsd/nffgInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="it.polito.dp2.NFFG" xmlns="it.polito.dp2.NFFG" elementFormDefault="qualified">
	<xs:annotation>
		<xs:documentation>
			This is the schema for NFFG
		</xs:documentation>
	</xs:annotation>
	<xs:element name="nffgs">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nffg" maxOccurs="unbounded" type="nffg_t">
					<xs:key name="node_key">
						<xs:selector xpath="node" />
						<xs:field xpath="@name" />
					</xs:key>
					<xs:key name="link_key">
						<xs:selector xpath="link" />
						<xs:field xpath="@name" />
					</xs:key>
					<xs:key name="policy_key">
						<xs:selector xpath="policy" />
						<xs:field xpath="@name" />
					</xs:key>

					<xs:keyref name="src_keyref" refer="node_key">
						<xs:selector xpath="link/src" />
						<xs:field xpath="@ref" />
					</xs:keyref>
					<xs:keyref name="dst_keyref" refer="node_key">
						<xs:selector xpath="link/dst" />
						<xs:field xpath="@ref" />
					</xs:keyref>
					<xs:keyref name="policy_src_keyref" refer="node_key">
						<xs:selector xpath="policy/src" />
						<xs:field xpath="@ref" />
					</xs:keyref>
					<xs:keyref name="policy_dst_keyref" refer="node_key">
						<xs:selector xpath="policy/dst" />
						<xs:field xpath="@ref" />
					</xs:keyref>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="nffg_key">
			<xs:selector xpath="nffg" />
			<xs:field xpath="@name" />
		</xs:key>
	</xs:element>

	<xs:complexType name="named_element_t">
		<xs:attribute name="name" type="name_t" use="required" />
	</xs:complexType>

	<xs:complexType name="nffg_t">
		<xs:complexContent>
			<xs:extension base="named_element_t">
				<xs:sequence>
					<xs:element name="node" minOccurs="0" maxOccurs="unbounded" type="node_t" />
					<xs:element name="link" minOccurs="0" maxOccurs="unbounded" type="link_t" />
					<xs:element name="policy" minOccurs="0" maxOccurs="unbounded" type="policy_t" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="node_t">
		<xs:complexContent>
			<xs:extension base="named_element_t">
				<xs:sequence>
					<xs:element name="functionality" type="functionality_t" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="link_t">
		<xs:complexContent>
			<xs:extension base="named_element_t">
				<xs:sequence>
					<xs:element name="src" type="node_ref_t" />
					<xs:element name="dst" type="node_ref_t" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="policy_t">
		<xs:complexContent>
			<xs:extension base="link_t">
				<xs:sequence>
					<xs:element name="result" type="result_t" />
					<xs:element name="functionality" minOccurs="0" maxOccurs="unbounded" type="functionality_t" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="functionality_t">
		<xs:restriction base="xs:string">
			<xs:enumeration value="firewall" />
			<xs:enumeration value="DPI" />
			<xs:enumeration value="NAT" />
			<xs:enumeration value="antispam" />
			<xs:enumeration value="web_cache" />
			<xs:enumeration value="VPN_gateway" />
			<xs:enumeration value="web_server" />
			<xs:enumeration value="web_client" />
			<xs:enumeration value="mail_server" />
			<xs:enumeration value="mail_client" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="node_ref_t">
		<xs:attribute name="ref" type="name_t" />
	</xs:complexType>

	<xs:simpleType name="name_t">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z][a-zA-Z\d]*" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="result_t">
		<xs:restriction base="xs:string">
			<xs:enumeration value="positive" />
			<xs:enumeration value="negative" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== MartinoMensio/DP2-Labs/Assignment 1/xsd/nffgInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<nffgs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="nffgInfo.xsd">
	<nffg name="Example1">
		<node name="WebClient1">
			<functionality>web_client</functionality>
		</node>
		<node name="NAT1">
			<functionality>NAT</functionality>
		</node>
		<node name="Firewall1">
			<functionality>firewall</functionality>
		</node>
		<node name="WebServer1">
			<functionality>web_server</functionality>
		</node>
		<link name="link1">
			<src name="WebClient1" />
			<dst name="NAT1" />
		</link>
		<link name="link2">
			<src name="NAT1" />
			<dst name="Firewall1" />
		</link>
		<link name="link3">
			<src name="Firewall1" />
			<dst name="WebServer1" />
		</link>
		<policy name="Policy1">
			<src name="WebClient1" />
			<dst name="WebServer1" />
			<result>true</result>
		</policy>
		<policy name="Policy2">
			<src name="WebServer1" />
			<dst name="WebClient1" />
			<result>false</result>
		</policy>
		<policy name="Policy3">
			<src name="WebClient1" />
			<dst name="WebServer1" />
			<result>true</result>
			<functionality>firewall</functionality>
		</policy>
	</nffg>

	<nffg name="Example2">
		<node name="WebClient1">
			<functionality>web_client</functionality>
		</node>
		<node name="NAT1">
			<functionality>NAT</functionality>
		</node>
		<node name="Firewall1">
			<functionality>firewall</functionality>
		</node>
		<node name="WebServer1">
			<functionality>web_server</functionality>
		</node>
		<link name="link1">
			<src name="WebClient1" />
			<dst name="NAT1" />
		</link>
		<link name="link2">
			<src name="NAT1" />
			<dst name="Firewall1" />
		</link>
		<link name="link3">
			<src name="Firewall1" />
			<dst name="WebServer1" />
		</link>
		<link name="link4">
			<src name="NAT1" />
			<dst name="WebClient1" />
		</link>
		<link name="link5">
			<src name="Firewall1" />
			<dst name="NAT1" />
		</link>
		<link name="link6">
			<src name="WebServer1" />
			<dst name="Firewall1" />
		</link>
		<policy name="Policy1">
			<src name="WebClient1" />
			<dst name="WebServer1" />
			<result>true</result>
		</policy>
		<policy name="Policy2">
			<src name="WebServer1" />
			<dst name="WebClient1" />
			<result>true</result>
		</policy>
		<policy name="Policy3">
			<src name="WebClient1" />
			<dst name="WebServer1" />
			<result>true</result>
			<functionality>firewall</functionality>
		</policy>
	</nffg>
</nffgs>
